version: "3"
services:
  volt-task-server:
    container_name: volt-task-server
    build:
      context: .
    env_file: .env
    depends_on:
      - volt-task-postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run dev
    networks:
      - volt-task-net

  volt-task-postgres:
    container_name: volt-task-postgres
    image: postgres:15.4-alpine
    env_file: .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - volt-task-net

networks:
  volt-task-net:
    driver: bridge