version: "3"
services:
  volt-task-server:
    container_name: volt-task-server
    build:
      context: .
    env_file:
      - .env
      - .local.env
    depends_on:
      - volt-task-postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run dev
    networks:
      - volt-task-net

  volt-task-postgres:
    container_name: volt-task-postgres
    restart: always
    image: postgres:15.4-alpine
    env_file:
      - .env
      - .local.env
    ports:
      - ${POSTGRES_PUBLIC_PORT}:${POSTGRES_PORT}
    networks:
      - volt-task-net

  volt-task-redis:
    container_name: volt-task-redis
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
      - .local.env
    ports:
      - ${REDIS_PUBLIC_PORT}:${REDIS_PORT}
    command: redis-server --requirepass $REDIS_PASSWORD
    networks:
      - volt-task-net

networks:
  volt-task-net:
    driver: bridge